spring:
  application:
    name: gateway
server:
  port: 10218
zuul:
  routes:
    # 面向服务的路由
    api-a:
      path: /client/**
      serviceId: client-server-caller #client-server-caller 对应的是注册中心的服务的名称

      #服务分发的方式是这样的，我们通过localhost：10216/client访问，实际是将地址映射到了client-test这个服务的地址上

    # 传统的路由
    api-b-url:
      path: /caller/**
      #由传统的路由模式，我们可以知道用户访问的路由路径为localhost:10215/caller，将服务映射到了http://localhost:10213
      url: http://localhost:10216/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10211/eureka/