#注册中心的名字
spring:
  application:
    name: my-eureka

#服务端口
server:
  port: 10211

#注册中心相关配置
eureka:
  server:
    # 配置关闭自我保护，并按需配置Eureka Server清理无效节点的时间间隔（5000ms）。
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    # 不将自己注册到注册中心
    register-with-eureka: false #fasle:
    # 因为自己是注册中心，因此不用检索服务信息
    fetch-registry: false        #true： Cannot execute request on any know server
    # 注册中心的地址
    service-url:
      defaultZone: http://localhost:10211/eureka/
  instance:
    prefer-ip-address: true

